"""empty message

Revision ID: 3cd4856b2a37
Revises: 6a06faa945bd
Create Date: 2025-12-03 19:21:30.995599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3cd4856b2a37'
down_revision: Union[str, Sequence[str], None] = '6a06faa945bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['approved_by'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('approved_date')
        batch_op.drop_column('approved_by')

    # ### end Alembic commands ###
