"""add mqtt_topic to sensor

Revision ID: 6a06faa945bd
Revises: 
Create Date: 2025-11-25 02:11:26.862597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6a06faa945bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mqtt_topic', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'Awi7LJfyyn6LPjg/15046220'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor', schema=None) as batch_op:
        batch_op.drop_column('mqtt_topic')

    # ### end Alembic commands ###
