"""empty message

Revision ID: b902bf103253
Revises: 3cd4856b2a37
Create Date: 2025-12-10 12:31:10.688940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b902bf103253'
down_revision: Union[str, Sequence[str], None] = '3cd4856b2a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_approved_by'), type_='foreignkey')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approved_date')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_approved_by'), 'user', ['approved_by'], ['id'])

    # ### end Alembic commands ###
